
version: '3.8'

services:
  mysql:
    image: mysql:8

    container_name: mysql_db_docker
    environment:
      MYSQL_ROOT_PASSWORD: 7685
      MYSQL_DATABASE: railway


    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 10s
      retries: 10


    ports:
        - "3307:3306"

    volumes:
      -  mysql_data:/var/lib/mysql
    networks:
      - scm-network



  springboot:
    image: kaushikjatin05/smart-contact-manager-final-springboot-jatinkau
    container_name: scm
    environment:
        MYSQL_USER: root
        MYSQL_PASSWORD: 7685
        MYSQL_HOST: mysql
        MYSQL_PORT: 3306
        MYSQL_DB: SmartContactManager
        SPRING_PROFILES_ACTIVE: docker



    ports:
      - "8080:8080"

    networks:
      - scm-network

    depends_on:
      mysql:
        condition: service_healthy





volumes:
  mysql_data:

networks:
  scm-network:
    driver: bridge


